[2025-08-08T02:54:13.913+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fake_data_dag.generate_fake_data manual__2025-08-08T02:54:12.701228+00:00 [queued]>
[2025-08-08T02:54:13.917+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fake_data_dag.generate_fake_data manual__2025-08-08T02:54:12.701228+00:00 [queued]>
[2025-08-08T02:54:13.918+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-08T02:54:13.929+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): generate_fake_data> on 2025-08-08 02:54:12.701228+00:00
[2025-08-08T02:54:13.932+0000] {standard_task_runner.py:60} INFO - Started process 205 to run task
[2025-08-08T02:54:13.933+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'fake_data_dag', 'generate_fake_data', 'manual__2025-08-08T02:54:12.701228+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/generate_fake_data_dag.py', '--cfg-path', '/tmp/tmpcygbreb7']
[2025-08-08T02:54:13.934+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask generate_fake_data
[2025-08-08T02:54:13.967+0000] {task_command.py:423} INFO - Running <TaskInstance: fake_data_dag.generate_fake_data manual__2025-08-08T02:54:12.701228+00:00 [running]> on host fce1a289a9f3
[2025-08-08T02:54:14.019+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fake_data_dag' AIRFLOW_CTX_TASK_ID='generate_fake_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-08T02:54:12.701228+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-08T02:54:12.701228+00:00'
[2025-08-08T02:54:14.050+0000] {logging_mixin.py:188} INFO - Error occurred: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(users_id_seq, 2200) already exists.
[2025-08-08T02:54:14.051+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-08T02:54:14.058+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fake_data_dag, task_id=generate_fake_data, execution_date=20250808T025412, start_date=20250808T025413, end_date=20250808T025414
[2025-08-08T02:54:14.106+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-08T02:54:14.117+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
